name: End To End migration [GEI] - 2.0
description: Perform a migration of ADO Pipeline from ADO to GitHub Actions
title: "End To End migration [GEI] - 2.0"
labels: ["migration", "gei"]
body:
  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description: Please enter the repositories that you would like to migrate from GitHub Enterprise Server to GitHub Enterprise Cloud
      placeholder: |
        https://github.com/your-org/your-repository-1
        https://github.com/your-org/your-repository-2
    validations:
      required: true
  - type: dropdown
    id: organization
    attributes:
      label: Target Organization
      description: Please select the Target Organization
      options:
        - mgmri-commerce
        - mgmri-dge
        - mgmri-source
        - mgmri-ciam
        - Core
        - mgmri-corp
        - mgmri-data
        - mgmri-eiam
        - mgmri-entertainment
        - mgmri-gaming
        - mgmri-hotel
        - mgmri-secops
        - mgmri-shared
    validations:
      required: true
  - type: dropdown
    id: visibility
    attributes:
      label: Target repository visibility
      description: Please select the visibility for the repositories on GitHub Enterprise Cloud after they have been migrated
      options:
        - Private
        - Internal
        - Mirror
    validations:
      required: true
  
  - type: input
    id: AZURE_DEVOPS_ORG
    attributes:
      label: "Azure DevOps Organization"
      description: "Enter the name of the Azure DevOps Organization"
      placeholder: "e.g., MGMResortsDigitalEngineering"
  - type: input
    id: AZURE_DEVOPS_PROJECT
    attributes:
      label: "Azure DevOps Project"
      description: "Enter the name of the Azure DevOps Project"
      placeholder: "e.g., Payment%20services"
  - type: input
    id: ADO2GHA_DOWNLOAD_BRANCH
    attributes:
      label: "ADO2GHA Download Branch"
      description: "Enter the name of the Branch to checkout for workflow and upload migrated GHA workflows"
      placeholder: "e.g., main"
  - type: dropdown
    id: PIPELINE_ACTION
    attributes:
      label: Pipeline Action
      description: Select Build or Release or Both.
      options:
        - 'Build'
        - 'Release'
        - 'Both'
      default: 2
    validations:
      required: true
  - type: input
    id: BUILD_PIPELINE_ID
    attributes:
      label: "Build Pipeline ID"
      description: "Enter the name of Pipeline ID"
      placeholder: "e.g., 1636"
  - type: input
    id: RELEASE_PIPELINE_ID
    attributes:
      label: "Release Pipeline ID"
      description: "Enter the name of Pipeline ID"
      placeholder: "e.g., 82"

  - type: dropdown
    id: locksourcerepo
    attributes:
      label: Lock Source Repository
      description: "No to leave it unlocked."
      options:
        - 'No'
    validations:
      required: true
