name: CI Main Workflow

on:
    push:
        branches:
            - main

jobs:
    calls-reusable-ci:
        uses: ./github/workflows/reusable-ci.yml@v1.0
        with:
            node_version: '16.x'

