name: Generate Org PAT Report
 
on:
  workflow_dispatch: # Run manually
  # schedule:
  #   - cron: "0 3 * * 1"   # Every Monday 3 AM UTC

  
jobs:
  generate-report:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
 
      - name: Generate PAT report
        run: |
          ORG_NAME="TestOrgProject01"
          TOKEN="${secrets.GIT_TOKEN}"
 
          echo "Token ID,Token Name,Created By,Created At,Expires At,Repositories,Permissions" > org_pat_report.csv
 
          response=$(curl -s -H "Authorization: Bearer $TOKEN" \
                           -H "Accept: application/vnd.github+json" \
                           "https://api.github.com/orgs/$ORG_NAME/personal-access-tokens")
 
          echo "$response" | jq -r '
            .personal_access_tokens[] |
            [
              .id,
              .token_name,
              .user.login,
              .created_at,
              .expires_at,
              (.repositories | map(.name) | join(";")),
              (.permissions | keys | join(";"))
            ] | @csv
          ' >> org_pat_report.csv
 
          echo "✅ Report generated: org_pat_report.csv"
 
      - name: Upload PAT report
        uses: actions/upload-artifact@v4
        with:
          name: org-pat-report
          path: org_pat_report.csv
 
   
