name: Shared GEI workflow
on:
  workflow_call:
    inputs:
      locksourcerepo:
        description: "Lock Source Repository after migration"
        required: true
        type: string
      AZURE_DEVOPS_ORG:
        description: "Azure DevOps Organization"
        required: true
        type: string
      AZURE_DEVOPS_PROJECT:
        description: "Azure DevOps Project"
        required: true
        type: string
      ADO2GHA_DOWNLOAD_BRANCH:
        description: "ADO2GHA migrated workflow will be downloaded into this branch"
        required: true
        type: string
  

permissions:
  contents: read
  issues: write

jobs:
   Commit-history-mapping:
    runs-on: ubuntu-latest
    name: Commit-history-mapping - ${{ github.repository }}
    

    steps:
      
      - name: Trigger Commit-history-mapping in Target
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          event-type: Commit-history-mapping-"${{ github.repository }}"
          client-payload: |
            {
              "repo_name": "${{ github.repository }}"
            
            }

   Trigger-combined-data-items:
    name: combined-data-items - ${{ github.repository }}
    runs-on: ubuntu-latest
    

    steps:
      - name: Print Variables
        run: |
          echo "Repository Name: "${{ github.repository }}""
          

      - name: Trigger Combined Data-Items Migration
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          event-type: combined-data-items-"${{ github.repository }}"
          client-payload: '{"repo_name": "${{ github.repository }}"}'
  
  
